### ISSUE TITLE
Make "resourceGroup" configurable-project creation time

### ISSUE THREAD

**Issue by yveszoundi** [Microsoft/azure-maven-archetypes#10]
It would be great to make the **resourceGroup** setting flexible, in a similar way than the **region** for which the default value is _westus_.

This would allow users to override the default _java-functions-group_ value while invoking the archetype. Otherwise, the user may initially forget about it, until deployment failures happen, when there are no user roles/permissions for creating resource groups.

**Comment by jdneo** [comment]
Hi @yveszoundi , are you looking for this: https://github.com/Microsoft/azure-maven-plugins/tree/master/azure-functions-maven-plugin#configurations?

**Comment by yveszoundi** [comment]
Hello @jdneo, I'm referring to the capability of providing a resource group "while creating" a new project with the archetype: "_archetype input parameters_" in simplistic words. I edited the issue title to make it more explicit.

```sh
mvn archetype:generate azure_functions_archetype_details -DazureResourceGroup=xxxx
```

**Comment by jdneo** [comment]
@yveszoundi Make sense. We will update this in the next release.
