### ISSUE TITLE
Change template so Azure Functions bundles work

### ISSUE THREAD

**Issue by jeffhollan** [microsoft/azure-maven-archetypes#108]
We are removing the requirement of having .NET Core SDK installed to use extensions with functions.  To use this, instead of doing `func extensions install` you can have a `host.json` that includes bundling information.  The runtime can than use pre-built extensions automatically without requiring a .NET build.

We should update the archetype template to include this.

```json
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
        }
}
```

**Comment by pragnagopa** [comment]
cc @soninaren @mattchenderson 

@jdneo / @Flanker32  - Can you please take look at the PR ? Let us know if you have any questions.

@jeffhollan  / @soninaren - What is the ETA for bundles annoucement?
