### ISSUE TITLE
appName parameter is ignored for azure functions

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/azure-maven-archetypes#136]
The VS Code extension runs a command like this to generate a new java project:
```
mvn archetype:generate -DarchetypeGroupId='com.microsoft.azure' -DarchetypeArtifactId='azure-functions-archetype' -DgroupId='com.function' -DartifactId='javart1' -Dversion='1.0-SNAPSHOT' -Dpackage='com.function' -DappName='myappname1' -B
```

In the past, it would set this in the new pom.xml:
```
<functionAppName>myappname1</functionAppName>
```

But now it's ignoring the `appName` parameter and always doing a name like this:
```
<functionAppName>javart1-20200227165500266</functionAppName>
```

Should the VS Code extension stop prompting for appName? I don't have a preference, but the README here seems to imply the parameter is still supported: https://github.com/microsoft/azure-maven-archetypes/tree/develop/azure-functions-archetype#azure-parameters

@Flanker32 @andxu Seems like this PR is what changed it: https://github.com/microsoft/azure-maven-archetypes/pull/128

**Comment by yucwan** [comment]
@Flanker32 Let's enable those parameters to unblock automation use case of the archetype

**Comment by Flanker32** [comment]
@EricJizbaMSFT Really sorry for the late reply, we have added the parameters back in the latest archetype release, here is the [release note](https://github.com/microsoft/azure-maven-archetypes/releases/tag/azure-functions-archetype-1.27)
