### ISSUE TITLE
javaVersion parameter is ignored

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/azure-maven-archetypes#154]
**Repro steps:**
Run a command like:
> mvn archetype:generate -DarchetypeGroupId='com.microsoft.azure' -DarchetypeArtifactId='azure-functions-archetype' -DjavaVersion='11' -DgroupId='com.function' -DartifactId='ja2' -Dversion='1.0-SNAPSHOT' -Dpackage='com.function' -DappName='ja2-1598029847902' -B

**Expected:**
"java.version" is set to 11 in pom.xml

**Actual:**
"java.version" is still 1.8

Seems like it has to do with the "javaVersion" logic being inside this "if" condition here: https://github.com/microsoft/azure-maven-archetypes/blob/develop/azure-functions-archetype/src/main/resources/META-INF/archetype-post-generate.groovy#L26

We always specify an appName in the Azure Functions extension, so it always skips that part

**Comment by Flanker32** [comment]
@EricJizbaMSFT Thanks again for your help, we have fixed the issue and released the archetype 1.31 and you may get it [here](https://repo.maven.apache.org/maven2/com/microsoft/azure/azure-functions-archetype/1.31/)
