### ISSUE TITLE
Default pricingTier not was set EP1  in docker pom.xml

### ISSUE THREAD

**Issue by SunnyChen1** [microsoft/azure-maven-archetypes#171]
**Environment:**
Maven: 3.6.3
JDK: 1.8.0-281
Azure-functions-archetype: 1.38-SNAPSHOT
**Reproduce Steps:**
1. Run mvn archetype:generate -DarchetypeCatalog=local -Ddocker to generate to function project
2. Open pom.xml, observe default pricingTier not was set EP1 

**Result:**
![image](https://user-images.githubusercontent.com/63633836/114525471-b44ebe00-9c78-11eb-8f39-dd72199ede9a.png)

**Comment by Flanker32** [comment]
default pricing tier for docker function has updated to EP1, so close this issue
