### ISSUE TITLE
The azure-functions-archetype artifact is not an archetype

### ISSUE THREAD

**Issue by nowitzkihuang** [microsoft/azure-maven-archetypes#178]
When I tried to create project for azure functions using azure-functions-archetype in eclipse, I encountered the problem as follows

Unable to create project from archetype [com.microsoft.azure:azure-functions-archetype:1.39 -> https://repo1.maven.org/maven2/]
The defined artifact is not an archetype

Can anyone help me solve the issue?
Thank you

**Comment by Flanker32** [comment]
@nowitzkihuang Could you please share your eclipse version and the screen shot of the issue, I tried with Eclipse 2021-03 and it seems works fine.
Besides, if the issue still reproduced, as a workaround, could you please try generate the project with `mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype` and import the result to Eclipse?

![image](https://user-images.githubusercontent.com/12445236/124735501-ad1e1000-df48-11eb-801d-28edc52af4ba.png)

![image](https://user-images.githubusercontent.com/12445236/124735462-a2fc1180-df48-11eb-9470-bbc14a515794.png)

**Comment by nowitzkihuang** [comment]
@Flanker32 Hi  the version of eclipse I use is as follows

![image](https://user-images.githubusercontent.com/77047161/124847051-afc24900-dfcc-11eb-8149-0a51d49d9bab.png)

and the screen shots are these
![image](https://user-images.githubusercontent.com/77047161/124847209-fdd74c80-dfcc-11eb-9dc7-063acbf1aba6.png)
![image](https://user-images.githubusercontent.com/77047161/124847266-15aed080-dfcd-11eb-8321-d95efe9064fa.png)
After I selected the azure functions archetype and jump to the next step, these are no properties as you show above
I also tried to use cmd, but it still failed, the screen shots show as follows, there is no option for azure function archetype can be selected
![image](https://user-images.githubusercontent.com/77047161/124847477-8950dd80-dfcd-11eb-853e-fbf1feedf78f.png)
![image](https://user-images.githubusercontent.com/77047161/124847536-a71e4280-dfcd-11eb-80fb-47d7a788155c.png)

**Comment by Flanker32** [comment]
@nowitzkihuang Thanks for your report, did you use proxy or mirror for maven? If so, could you please try the archetype command without mirror?

Besides, here is the [link](https://repo1.maven.org/maven2/com/microsoft/azure/azure-functions-archetype/1.39/) for functions archetype in maven repository, could you please try whether its reachable in your machine? If so, could you please try clean the cached archetype in `{your_m2_home}\repository\com\microsoft\azure\azure-functions-archetype` and re-run the archetype command?

**Comment by nowitzkihuang** [comment]
@Flanker32 Hi thank you for your reply, I fixed the issue after I got the settings.xml from my colleague and refreshed the maven repository. I think it may get the something wrong when catching the archetype from my computer. Thank you for your help again.
