### ISSUE TITLE
Functions archetypes should use V3 bundle version when available

### ISSUE THREAD

**Issue by mattchenderson** [microsoft/azure-maven-archetypes#182]
_This is a tracking item for action to take once the V3 bundle exists in the main bundle ID._

The current host.json that is checked in uses V1 of the bundles:

https://github.com/microsoft/azure-maven-archetypes/blob/64e3439e5c3d9d6bee13623b011644ce4b26320f/azure-functions-archetype/src/main/resources/archetype-resources/host.json#L1-L7

https://github.com/microsoft/azure-maven-archetypes/issues/181 tracks making this V2 now.

However, once the V3 bundle is finalized, we should update it to use V3:

```json
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
  } 
}
```

**Comment by Flanker32** [comment]
Function archetype has already updated to V3 bundle, so close this issue
