### ISSUE TITLE
maven archetype 1.56 generates project using old packages

### ISSUE THREAD

**Issue by Bill-XU** [Microsoft/azure-maven-archetypes#223]
hello,
trying to generate java project using following command:
`mvn archetype:generate -DarchetypeGroupId="com.microsoft.azure" -DarchetypeArtifactId="azure-functions-archetype" -Dversion=1.56 -DjavaVersion=11`

but argument javaVersion is ignored, version in generated pom.xml is 1.8 still

if try to build generated project under java 11, many incompatible exceptions occur,
such as JAXBException not found (not available in Java 9+, fixed in newer version of azure-functions-maven-plugin, rather than version 0.1.4 configured in archetype ),
FunctionName not found (package changed after azure functions core library being separated into different libraries)

is it possible to add some up-to-date support in this archetype?

best regards
bill

**Comment by Flanker32** [comment]
@Bill-XU Thanks for your report. It seems that you are still using older archetype, could you please try the following command? (Please replace `-Dversion` to `-DarchetypeVersion` )
```
mvn archetype:generate -DarchetypeGroupId="com.microsoft.azure" -DarchetypeArtifactId="azure-functions-archetype" -DarchetypeVersion=1.56 -DjavaVersion=11
```

**Comment by Bill-XU** [comment]
> @Bill-XU Thanks for your report. It seems that you are still using older archetype, could you please try the following command? (Please replace `-Dversion` to `-DarchetypeVersion` )
> 
> ```
> mvn archetype:generate -DarchetypeGroupId="com.microsoft.azure" -DarchetypeArtifactId="azure-functions-archetype" -DarchetypeVersion=1.56 -DjavaVersion=11
> ```

thank you for pointing out my mistakes, after changing -Dversion to -DarchetypeVersion, the latest archetype is applied.

i noticed that in ms learn the example for using archetypes do not come with such version parameter, which will cause using older archetype. maybe you should consider update it and provide a different version for java 11, or just mention that -DarchetypeVersion should also be specified when using -DjavaVersion=11 or any other later version.

anyway, thank you for you advice
