### ISSUE TITLE
mvn azure-functions:package doesn't work`

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/azure-maven-archetypes#28]
When I run `mvn azure-functions:package` it creates a target directory that only has a host.json.  Doing `mvn package` works fine.  Not sure why the former doesn't work, but should likely either remove or fix.

**Comment by jdneo** [comment]
@jeffhollan Moving to plugin repo: https://github.com/Microsoft/azure-maven-plugins/issues/198
