### ISSUE TITLE
Version name - should be 1.1-beta

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-maven-archetypes#3]
instead of a snapshot. Also, we should use 1.1 consistently everywhere. There are some traces of 1.0-Snapshot when you use the archetype

**Comment by xscript** [comment]
@selvasingh  The snapshot versions are used for private preview. For public preview, we are using verion `1.0` (in Maven central).
Also, I didn't see anywhere else using 1.1-beta. Could you explain more about it?

**Comment by brunoborges** [comment]
@selvasingh is this issue still valid?

**Comment by jdneo** [comment]
Closing this issue since this is inactive for a long time. Please feel free to reopen it if anyone find this is a problem.
