### ISSUE TITLE
Standardize Git Branches and Tags

### ISSUE THREAD

**Issue by brunoborges** [Microsoft/azure-maven-archetypes#35]
It is very common practice, on GitHub and at almost all Azure/Microsoft repositories to use master branch as the upstream (latest working/released version) as well the default branch of the GitHub repository.

Tags are good to use to point to previous released versions.

For tags, something that points to the source code of the specific released artifact and version.

Would be good to standardize it this way.
---------------------------------------------------------

Updated by @jdneo

We have two tasks here.
- [x] rename the tags to remove `v`
- [x] change the branch model

**Comment by jdneo** [comment]
@brunoborges Thanks for the suggestion.

Just want to double confirm, the action we should take is rename the tags from `azure-functions-archetype-v1.11` -> `azure-functions-archetype-1.11`.

Am I right?

**Comment by brunoborges** [comment]
That is the minor suggestion, yes. 

Most importantly is to have `master` being the default branch and the upstream, latest released version.

**Comment by jdneo** [comment]
I see. So we will have two branches:
- the default `master` is the latest released version. 
- new feature code goes to `develop`.

Right?

**Comment by brunoborges** [comment]
Correct. We could also use feature branch practice for major features.

**Comment by jdneo** [comment]
I see. Will start this pattern from `1.12`

**Comment by jdneo** [comment]
@brunoborges Done.
