### ISSUE TITLE
Discuss about the parent pom file in this repo

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-maven-archetypes#36]
For now, we have a parent pom here: https://github.com/Microsoft/azure-maven-archetypes/blob/master/pom.xml

And the function archetype is treated as a submodule.

@brunoborges Do you think it is necessary to organize them as multi-module project? How about each archetype becomes a simple folder?

**Comment by brunoborges** [comment]
I think we can take the same approach as the maven plugin repo. We use multi-modules to take advantage of shared configurations, but release archetypes independently (and don't release to Maven Central the parent, because it is not needed at all).

**Comment by jdneo** [comment]
I see.
