### ISSUE TITLE
Need some validation for parameter values

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-maven-archetypes#47]
Plugin name and version
azure-maven-archetypes: 1.14

Repro steps:
1. Invalid value of artifactid
![image](https://user-images.githubusercontent.com/22470312/44197775-36a61d80-a172-11e8-84a1-f46f9e1464ef.png)
2. The generated pom.xml
![image](https://user-images.githubusercontent.com/22470312/44197617-b5e72180-a171-11e8-87f5-0b112f388acf.png)
3.  Execute Maven goal
![image](https://user-images.githubusercontent.com/22470312/44197628-baabd580-a171-11e8-9f52-7038c9296ac1.png)

**Comment by jdneo** [comment]
Fixed in #53
