### ISSUE TITLE
Method name conflicts with the default name of function class 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-maven-archetypes#49]
The extension I used is vscode azure functions extension
Steps:
1. Create a java azure function project
2. Open command palette and select command: Azure Functions: Create Function...
3. Choose HttpTrigger
4. Give the function name: HttpTriggerJava

![image](https://user-images.githubusercontent.com/22470312/44254778-6c143f00-a236-11e8-88f9-81229ad9586a.png)

**Comment by jdneo** [comment]
Fixed in #54
