### ISSUE TITLE
Considering add FUNCTIONS_WORKER_RUNTIME=java into the <appSetting> field

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-maven-archetypes#58]
According to the new App Service Annoucement: https://github.com/Azure/app-service-announcements/issues/129

> Choose a language for a Function App
> - If your app contains functions with a single language for example only CSharp functions, then no action is needed
> - If your app contains functions with multiple languages for example, CSharp and JavaScript then
Select a language: by adding an App setting named FUNCTIONS_WORKER_RUNTIME
>   - Set value to dotnet for CSharp/Fsharp/Precompiled samples
>   - Set value to node for JavaScript samples
>   - Set value to java for run Java samples

We should consider whether we need to add `FUNCTIONS_WORKER_RUNTIME`: `java` into the application settings of the function archetype.

**Comment by jdneo** [comment]
@pragnagopa Any thoughts here?

**Comment by pragnagopa** [comment]
Yes.  archetype needs to be updated. Thanks!
