### ISSUE TITLE
Lower case values generated in function.json

### ISSUE THREAD

**Issue by pragnagopa** [Microsoft/azure-maven-archetypes#63]
Key-Value pairs in function.json need to be camelCased. 
Following is fields are inconsistent and when opened in VS show schema validation errors
```  
    "webHookType" : "NONE",
     "methods" : [ "GET", "POST" ]
```
see sample function.json here
https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/HttpTrigger-JavaScript/function.json

**Comment by jdneo** [comment]
Moving to https://github.com/Microsoft/azure-maven-plugins/issues/386
